<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('productos')->insert([
            ["nombre"=>"PAN BOTON","rubro_id"=>1],
            ["nombre"=>"PORCION DE TOSTADA","rubro_id"=>1],
            ["nombre"=>"BEBIDAS CERVEZA HUARI 1/2","rubro_id"=>2],
            ["nombre"=>"BEBIDAS AGUA VITAL","rubro_id"=>2],
            ["nombre"=>"AGUA","rubro_id"=>2],
            ["nombre"=>"CERVEZA","rubro_id"=>2],
            ["nombre"=>"LICOR DE DURAZNO ","rubro_id"=>2],
            ["nombre"=>"COCA COLA 1/2 PAQUETE","rubro_id"=>2],
            ["nombre"=>"JARRA DE MOKONCHINCHI","rubro_id"=>2],
            ["nombre"=>"JARRA DE TOSTADA","rubro_id"=>2],
            ["nombre"=>"JGO UVA","rubro_id"=>2],
            ["nombre"=>"JGO UVA C AGUA","rubro_id"=>2],
            ["nombre"=>"JGO SANDIA","rubro_id"=>2],
            ["nombre"=>"JGO SANDIA C AGUA","rubro_id"=>2],
            ["nombre"=>"JGO MANGO","rubro_id"=>2],
            ["nombre"=>"JGO MANGO C AGUA","rubro_id"=>2],
            ["nombre"=>"COMBO PRIMAVERA","rubro_id"=>2],
            ["nombre"=>"TARTA DE MANZANA","rubro_id"=>3],
            ["nombre"=>"LENGUA DE SUEGRA","rubro_id"=>3],
            ["nombre"=>"ALFAJOR CON MAJAR","rubro_id"=>3],
            ["nombre"=>"NIDITO","rubro_id"=>3],
            ["nombre"=>"GOLOSOS","rubro_id"=>3],
            ["nombre"=>"BERLINES","rubro_id"=>3],
            ["nombre"=>"DONNUTS","rubro_id"=>3],
            ["nombre"=>"NAPOLEONES","rubro_id"=>3],
            ["nombre"=>"CROISSANT C/DULCE DE LECHE","rubro_id"=>3],
            ["nombre"=>"BROUNI DE  FRUTILLA","rubro_id"=>3],
            ["nombre"=>"ALFAJOR CREMA PASTELERA","rubro_id"=>3],
            ["nombre"=>"BOMBITAS","rubro_id"=>3],
            ["nombre"=>"ECLERS","rubro_id"=>3],
            ["nombre"=>"TARTALETAS DE FRUTAS","rubro_id"=>3],
            ["nombre"=>"DONUUTS CREMA PASTELERA","rubro_id"=>3],
            ["nombre"=>"TARTALETA DE LIMON","rubro_id"=>3],
            ["nombre"=>"TRUFAS DE CHOCOLATE","rubro_id"=>3],
            ["nombre"=>"BROUNI DE CHOCOLATE","rubro_id"=>3],
            ["nombre"=>"EMPANADAS DE HOJA","rubro_id"=>3],
            ["nombre"=>"MEDIA LUNA","rubro_id"=>3],
            ["nombre"=>"CROISSANT DULCE","rubro_id"=>3],
            ["nombre"=>"CONITOS CON CREMA","rubro_id"=>3],
            ["nombre"=>"OJITO DE BUEY","rubro_id"=>3],
            ["nombre"=>"POSTRE TRES LECHES","rubro_id"=>3],
            ["nombre"=>"CROISSANT CON MANJAR","rubro_id"=>3],
            ["nombre"=>"BUDIN DE CHOCOLATE","rubro_id"=>3],
            ["nombre"=>"MINI PAT MASITAS","rubro_id"=>3],
            ["nombre"=>"POSTRE TIRAMIZU","rubro_id"=>3],
            ["nombre"=>"POSTRE REQUESON","rubro_id"=>3],
            ["nombre"=>"GALLETAS NAVIDEÑAS","rubro_id"=>3],
            ["nombre"=>"BUDIN NAVIDEÑO","rubro_id"=>3],
            ["nombre"=>"PACK DE MASITAS","rubro_id"=>3],
            ["nombre"=>"PAN PIZA","rubro_id"=>4],
            ["nombre"=>"ENRROLADO QUESO JAMON","rubro_id"=>4],
            ["nombre"=>"ROLLITOS DE QUESO","rubro_id"=>4],
            ["nombre"=>"EMPANADAS DE QUESO","rubro_id"=>4],
            ["nombre"=>"PALITOS","rubro_id"=>4],
            ["nombre"=>"CROISSANT DE QUESO","rubro_id"=>4],
            ["nombre"=>"CROISSANT DE QUESO Y JAMON","rubro_id"=>4],
            ["nombre"=>"CUÑAPES","rubro_id"=>4],
            ["nombre"=>"ENRROLLADO DE QUESO","rubro_id"=>4],
            ["nombre"=>"TORTA ROSA NEGRA","rubro_id"=>5],
            ["nombre"=>"TORTA CHOCOLATE","rubro_id"=>5],
            ["nombre"=>"TORTA CANASTA GRANDE","rubro_id"=>5],
            ["nombre"=>"TORTA CANASTA PEQUEÑA","rubro_id"=>5],
            ["nombre"=>"TORTA DE FRUTILLA GRANDE","rubro_id"=>5],
            ["nombre"=>"TORTA DE FRUTILLA MEDIANA","rubro_id"=>5],
            ["nombre"=>"TORTA DE FRUTILLA PEQUEÑA","rubro_id"=>5],
            ["nombre"=>"TORTA DE DURAZNO GRANDE","rubro_id"=>5],
            ["nombre"=>"TORTA DE DURAZNO MEDIANA","rubro_id"=>5],
            ["nombre"=>"TORTA DE DURAZNO PEQUEÑA","rubro_id"=>5],
            ["nombre"=>"TORTA DE MOCA GRANDE","rubro_id"=>5],
            ["nombre"=>"TORTA DE MOCA MEDIANA","rubro_id"=>5],
            ["nombre"=>"TORTA DE MOCA PEQUEÑA","rubro_id"=>5],
            ["nombre"=>"TORTA TROPICAL GRANDE","rubro_id"=>5],
            ["nombre"=>"TORTA TROPICA PEQUEÑA","rubro_id"=>5],
            ["nombre"=>"TORTA CHOCOVAINILLA GRANDE","rubro_id"=>5],
            ["nombre"=>"TORTA CHOCOVAINILLA PEQUEÑA","rubro_id"=>5],
            ["nombre"=>"TORTA S NEGRA GRANDE","rubro_id"=>5],
            ["nombre"=>"TORTA S NEGRA MEDIANA","rubro_id"=>5],
            ["nombre"=>"TORTA S NEGRA PEQUEÑA","rubro_id"=>5],
            ["nombre"=>"TORTA DE UVA","rubro_id"=>5],
            ["nombre"=>"TORTA CHOCOLATE ALEMAN GRANDE","rubro_id"=>5],
            ["nombre"=>"TORTA CHOCOLATE ALEMAN PEQUEÑA","rubro_id"=>5],
            ["nombre"=>"PORCION DE TORTA","rubro_id"=>5],
            ["nombre"=>"TORTA ARLEQUIN","rubro_id"=>5],
            ["nombre"=>"TORTA CHOCO MERENGUE GRANDE","rubro_id"=>5],
            ["nombre"=>"TORTA CHOCO MERENGUE PEQUEÑA","rubro_id"=>5],
            ["nombre"=>"TORTA DE NUEZ GRANDE","rubro_id"=>5],
            ["nombre"=>"TORTA NUEZ MEDIANA","rubro_id"=>5],
            ["nombre"=>"TORTA NUEZ PEQUEÑA","rubro_id"=>5],
            ["nombre"=>"TORTA PIÑA GRANDE","rubro_id"=>5],
            ["nombre"=>"TORTA TIRAMIZU ","rubro_id"=>5],
            ["nombre"=>"TORTA CONTRATO","rubro_id"=>5],
            ["nombre"=>"QUEQUE DE NARANJA","rubro_id"=>5],
            ["nombre"=>"PORCION QUEQUE NARANJA","rubro_id"=>5],
            ["nombre"=>"BRAZO GITANO","rubro_id"=>5],
            ["nombre"=>"PORCION BRAZO GITANO","rubro_id"=>5],
            ["nombre"=>"PORCION TORTA ESPECIAL","rubro_id"=>5],
            ["nombre"=>"PORCION CHESSCAKE","rubro_id"=>5],
            ["nombre"=>"CHESSCAKE FRUTAS","rubro_id"=>5],
            ["nombre"=>"MUSH MIXTO","rubro_id"=>5],
            ["nombre"=>"TORTA TRES LECHES","rubro_id"=>5],
            ["nombre"=>"TORTA MIXTA","rubro_id"=>5],
            ["nombre"=>"TORTA CHOCO FRUTILLA","rubro_id"=>5],
            ["nombre"=>"TORTA FESTIVAL","rubro_id"=>5],
            ["nombre"=>"TORTA TRES LECHES PEQUEÑA","rubro_id"=>5],
            ["nombre"=>"TORTA OREO","rubro_id"=>5],
            ["nombre"=>"TORTA ROSA BLANCA","rubro_id"=>5],
            ["nombre"=>"X 2 TORTA CON HELADO","rubro_id"=>5],
            ["nombre"=>"ROSCAS NAVIDEÑAS","rubro_id"=>5],
            ["nombre"=>"TORTA CAPUCHINO","rubro_id"=>5],
            ["nombre"=>"TORTA CHOCO NUEZ","rubro_id"=>5],
            ["nombre"=>"DESAYUNO SUPER MAMA","rubro_id"=>5],
            ["nombre"=>"JGO FRUTILLA","rubro_id"=>6],
            ["nombre"=>"JGO FRUTILLA C/AGUA","rubro_id"=>6],
            ["nombre"=>"JGO DE LIMON","rubro_id"=>6],
            ["nombre"=>"JGO DE LIMON C/AGUA","rubro_id"=>6],
            ["nombre"=>"JGO DE DURAZNO","rubro_id"=>6],
            ["nombre"=>"JGO DE DURAZNO C/AGUA","rubro_id"=>6],
            ["nombre"=>"JGO DE MANZANA","rubro_id"=>6],
            ["nombre"=>"JGO DE MANZANA C/AGUA","rubro_id"=>6],
            ["nombre"=>"JGO PLATANO","rubro_id"=>6],
            ["nombre"=>"JGO PLATANO C/AGUA","rubro_id"=>6],
            ["nombre"=>"JGO DE NARANJA","rubro_id"=>6],
            ["nombre"=>"JGO DE NARANJA C/AGUA","rubro_id"=>6],
            ["nombre"=>"1/2 JARRA LIMA","rubro_id"=>6],
            ["nombre"=>"JARRA LIMA","rubro_id"=>6],
            ["nombre"=>"JARRA NARANJA","rubro_id"=>6],
            ["nombre"=>"1/2 JARRA NARANJA","rubro_id"=>6],
            ["nombre"=>"JGO PAPAYA","rubro_id"=>6],
            ["nombre"=>"JGO PAPAYA / AGUA","rubro_id"=>6],
            ["nombre"=>"JARRA DE LIMON","rubro_id"=>6],
            ["nombre"=>"1/2 JARRA DE LIMON","rubro_id"=>6],
            ["nombre"=>"JGO DE PIÑA","rubro_id"=>6],
            ["nombre"=>"JGO DE PIÑA C/AGUA","rubro_id"=>6],
            ["nombre"=>"JARRA DE FRUTILLA","rubro_id"=>6],
            ["nombre"=>"1/2 JARRA DE FRUTILLA","rubro_id"=>6],
            ["nombre"=>"JARRA PAPAYA","rubro_id"=>6],
            ["nombre"=>"1/2 JARRA DE PAPAYA","rubro_id"=>6],
            ["nombre"=>"JARRA DE PIÑA","rubro_id"=>6],
            ["nombre"=>"1/2 JARRA DE PIÑA","rubro_id"=>6],
            ["nombre"=>"JARRA  MIXTA","rubro_id"=>6],
            ["nombre"=>"1/2 JARRA MIXTA","rubro_id"=>6],
            ["nombre"=>"ZUMO DE NARANJA","rubro_id"=>6],
            ["nombre"=>"JGO MIXTO","rubro_id"=>6],
            ["nombre"=>"JARRA DE MANZANA","rubro_id"=>6],
            ["nombre"=>"1/2 JARRA DE MANZANA","rubro_id"=>6],
            ["nombre"=>"JGO TUMBO","rubro_id"=>6],
            ["nombre"=>"JGO TUMBO  AGUA","rubro_id"=>6],
            ["nombre"=>"1/2 JARRA DE TUMBO ","rubro_id"=>6],
            ["nombre"=>"JARRA DE TUMBO","rubro_id"=>6],
            ["nombre"=>"1/2 JARRA DURAZNO","rubro_id"=>6],
            ["nombre"=>"JARRA DE DURAZNO","rubro_id"=>6],
            ["nombre"=>"JGO MANDARINA","rubro_id"=>6],
            ["nombre"=>"JGO MADARINA C AGUA","rubro_id"=>6],
            ["nombre"=>"COMBO AMOR","rubro_id"=>6],
            ["nombre"=>"COCACOLA 1/2 ","rubro_id"=>7],
            ["nombre"=>"SPRITE 1/2","rubro_id"=>7],
            ["nombre"=>"FANTA 1/2","rubro_id"=>7],
            ["nombre"=>"AQUARIOS","rubro_id"=>7],
            ["nombre"=>"GASEOSA 1 LITRO","rubro_id"=>7],
            ["nombre"=>"COCA COLA DE 300 ML","rubro_id"=>7],
            ["nombre"=>"HAMB SIMPLE","rubro_id"=>8],
            ["nombre"=>"HAMB SIMPLE C/PAPAS","rubro_id"=>8],
            ["nombre"=>"COMBO 1","rubro_id"=>8],
            ["nombre"=>"COMBO 3","rubro_id"=>8],
            ["nombre"=>"COMBO 4","rubro_id"=>8],
            ["nombre"=>"COMBO 5","rubro_id"=>8],
            ["nombre"=>"COMBO 6","rubro_id"=>8],
            ["nombre"=>"SUPER HAMBURGUESA","rubro_id"=>8],
            ["nombre"=>"HAMB SIMPLE 2","rubro_id"=>8],
            ["nombre"=>"HAMB SIMPLE  2 C PAPA","rubro_id"=>8],
            ["nombre"=>"HAMB SIMPLE 3","rubro_id"=>8],
            ["nombre"=>"HAMB SIMPLE 3 CON PAPAS","rubro_id"=>8],
            ["nombre"=>"HAMB DOBLE 4","rubro_id"=>8],
            ["nombre"=>"HAMB DOBLE 4 C PAPAS","rubro_id"=>8],
            ["nombre"=>"HAMBU DOBLE 5","rubro_id"=>8],
            ["nombre"=>"HAMB DOBLE 5 C PAPAS","rubro_id"=>8],
            ["nombre"=>"HAMB DOBLE 6","rubro_id"=>8],
            ["nombre"=>"HAMB DOBLE 6 C PAPAS","rubro_id"=>8],
            ["nombre"=>"SUPER HAMBU C PAPAS","rubro_id"=>8],
            ["nombre"=>"COMBO HALLOWEN HAMBURGUESA","rubro_id"=>8],
            ["nombre"=>"COMBO ESCOLAR","rubro_id"=>9],
            ["nombre"=>"COMBO TRIO","rubro_id"=>9],
            ["nombre"=>"COMBO DUO","rubro_id"=>9],
            ["nombre"=>"SUPER COMBO","rubro_id"=>9],
            ["nombre"=>"PIPOCAS DE POLLO","rubro_id"=>9],
            ["nombre"=>"POLLO ENTERO","rubro_id"=>9],
            ["nombre"=>"BIDON DE PIPOCA DE POLLO","rubro_id"=>9],
            ["nombre"=>"X 2 PIPOCAS DE POLLO","rubro_id"=>9],
            ["nombre"=>"COMBO HALLOWEN ESCOLAR","rubro_id"=>9],
            ["nombre"=>"COMBO SUPER GRINCH","rubro_id"=>9],
            ["nombre"=>"AGUA","rubro_id"=>9],
            ["nombre"=>"AGUA","rubro_id"=>9],
            ["nombre"=>"AGUA","rubro_id"=>9],

            
        ]);
    }
}
