<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('productos')->insert([
            ["nombre"=>"CAFE","descripcion"=>"Cafe negro","precio"=>"7","rubro_id"=>'1'],
            ["nombre"=>"TE","descripcion"=>"Te","precio"=>"6","rubro_id"=>'1'],
            ["nombre"=>"MATES","descripcion"=>"Mate Natural","precio"=>"6","rubro_id"=>'1'],
            ["nombre"=>"TE CON TE ","descripcion"=>"Te con singani","precio"=>"15","rubro_id"=>'1'],
            ["nombre"=>"TODY CON LECHE ","descripcion"=>"Tody con leche","precio"=>"12","rubro_id"=>'1'],

            ["nombre"=>"CAPUCHINO ","descripcion"=>"Cafe, crema y canela","precio"=>"12","rubro_id"=>'2'],
            ["nombre"=>"MOKACHINO ","descripcion"=>"Cafe, chocolate y crema","precio"=>"14","rubro_id"=>'2'],
            ["nombre"=>"MOKACHINO ESPUMOSO","descripcion"=>"Cafe, leche espumante y baño de chocolate","precio"=>"15","rubro_id"=>'2'],
            ["nombre"=>"CAFE CORTADO ","descripcion"=>"Cafe con chorrito de leche evaporada","precio"=>"12","rubro_id"=>'2'],
            ["nombre"=>"CAFE CARAMELO","descripcion"=>"Cafe, dulce de leche y crema","precio"=>"16","rubro_id"=>'2'],
   
            ["nombre"=>"CAPUCHINO HELADO","descripcion"=>"Frapeado de cafe, helado de capuchino y crema","precio"=>"23","rubro_id"=>'3'],
            ["nombre"=>"FRAPUCHINO","descripcion"=>"Frapeado de cafe, chocolate y crema","precio"=>"23","rubro_id"=>'3'],
            ["nombre"=>"TE HELADO","descripcion"=>"Frapeado de te y limon","precio"=>"18","rubro_id"=>'3'],
            ["nombre"=>"FRAPPE CON YOGURT","descripcion"=>"Frapeado de yogurt con frutas naturales de la temporada","precio"=>"23","rubro_id"=>'3'],

            ["nombre"=>"LICOR DE DURAZNO","descripcion"=>"Licor de durazno, cafe expresso y crema","precio"=>"22","rubro_id"=>'4'],
            ["nombre"=>"CAFE IRLANDES","descripcion"=>"Cafe con whisky y crema","precio"=>"22","rubro_id"=>'4'],
            ["nombre"=>"CAFE FRANCES","descripcion"=>"Con coñac, crema y canela molida","precio"=>"22","rubro_id"=>'4'],

            ["nombre"=>"LIMON C/AGUA","descripcion"=>"Jugo de limon con agua","precio"=>"8.5","rubro_id"=>'5'],
            ["nombre"=>"LIMON C/LECHE","descripcion"=>"Jugo de limon con leche","precio"=>"10","rubro_id"=>'5'],
            ["nombre"=>"FRUTILLA C/AGUA","descripcion"=>"Jugo de Frutilla con agua","precio"=>"8.5","rubro_id"=>'5'],
            ["nombre"=>"FRUTILLA C/LECHE","descripcion"=>"Jugo de Frutilla con leche","precio"=>"10","rubro_id"=>'5'],
            ["nombre"=>"DURAZNO C/AGUA","descripcion"=>"Jugo de Durazno con agua","precio"=>"10","rubro_id"=>'5'],
            ["nombre"=>"DURAZNO C/LECHE","descripcion"=>"Jugo de Durazno con leche","precio"=>"12","rubro_id"=>'5'],
            ["nombre"=>"PAPAYA C/AGUA","descripcion"=>"Jugo de papaya con agua","precio"=>"8.5","rubro_id"=>'5'],
            ["nombre"=>"PAPAYA C/LECHE","descripcion"=>"Jugo de papaya con leche","precio"=>"10","rubro_id"=>'5'],
            ["nombre"=>"PLATANO C/AGUA","descripcion"=>"Jugo de platano con agua","precio"=>"8.5","rubro_id"=>'5'],
            ["nombre"=>"PLATANO C/LECHE","descripcion"=>"Jugo de platano con leche","precio"=>"10","rubro_id"=>'5'],
            ["nombre"=>"PIÑA C/AGUA","descripcion"=>"Jugo de piña con agua","precio"=>"0","rubro_id"=>'5'],
            ["nombre"=>"PIÑA C/LECHE","descripcion"=>"Jugo de piña con leche","precio"=>"0","rubro_id"=>'5'],
            ["nombre"=>"NARANJA C/AGUA","descripcion"=>"Jugo de naranja con agua","precio"=>"8.5","rubro_id"=>'5'],
            ["nombre"=>"NARANJA C/LECHE","descripcion"=>"Jugo de naranja con leche","precio"=>"10","rubro_id"=>'5'],
            ["nombre"=>"LIMA C/AGUA","descripcion"=>"Jugo de lima con agua","precio"=>"0","rubro_id"=>'5'],
            ["nombre"=>"LIMA C/LECHE","descripcion"=>"Jugo de lima con leche","precio"=>"0","rubro_id"=>'5'],
            ["nombre"=>"MANZANA C/AGUA","descripcion"=>"Jugo de manzana con agua","precio"=>"8.5","rubro_id"=>'5'],
            ["nombre"=>"MANZANA C/LECHE","descripcion"=>"Jugo de manzana con leche","precio"=>"10","rubro_id"=>'5'],
            ["nombre"=>"TUMBO C/AGUA","descripcion"=>"Jugo de tumbo con agua","precio"=>"0","rubro_id"=>'5'],
            ["nombre"=>"TUMBO C/LECHE","descripcion"=>"Jugo de tumbo con leche","precio"=>"0","rubro_id"=>'5'],
            ["nombre"=>"MARACUYA C/AGUA","descripcion"=>"Jugo de maracuya con agua","precio"=>"0","rubro_id"=>'5'],
            ["nombre"=>"MARACUYA C/LECHE","descripcion"=>"Jugo de maracuya con leche","precio"=>"0","rubro_id"=>'5'],
            ["nombre"=>"UVA C/AGUA","descripcion"=>"Jugo de uva con agua","precio"=>"0","rubro_id"=>'5'],
            ["nombre"=>"UVA C/LECHE","descripcion"=>"Jugo de uva con leche","precio"=>"0","rubro_id"=>'5'],

            ["nombre"=>"JARRA DE LIMON","descripcion"=>"Jugo de limon","precio"=>"35","rubro_id"=>'6'],
            ["nombre"=>"1/2 JARRA DE LIMON","descripcion"=>"Jugo de limon","precio"=>"25","rubro_id"=>'6'],
            ["nombre"=>"JARRA DE FRUTILLA","descripcion"=>"Jugo de Frutilla","precio"=>"35","rubro_id"=>'6'],
            ["nombre"=>"1/2 JARRA DE FRUTILLA","descripcion"=>"Jugo de Frutilla","precio"=>"25","rubro_id"=>'6'],
            ["nombre"=>"JARRA DE DURAZNO","descripcion"=>"Jugo de Durazno","precio"=>"35","rubro_id"=>'6'],
            ["nombre"=>"1/2 JARRA DE DURAZNO","descripcion"=>"Jugo de Durazno","precio"=>"25","rubro_id"=>'6'],
            ["nombre"=>"JARRA DE PAPAYA","descripcion"=>"Jugo de papaya","precio"=>"35","rubro_id"=>'6'],
            ["nombre"=>"1/2 JARRA DE PAPAYA","descripcion"=>"Jugo de papaya","precio"=>"25","rubro_id"=>'6'],
            ["nombre"=>"JARRA DE PLATANO","descripcion"=>"Jugo de platano","precio"=>"35","rubro_id"=>'6'],
            ["nombre"=>"1/2 JARRA DE PLATANO","descripcion"=>"Jugo de platano","precio"=>"25","rubro_id"=>'6'],
            ["nombre"=>"JARRA DE PIÑA","descripcion"=>"Jugo de piña","precio"=>"0","rubro_id"=>'6'],
            ["nombre"=>"1/2 JARRA DE PIÑA","descripcion"=>"Jugo de piña","precio"=>"0","rubro_id"=>'6'],
            ["nombre"=>"JARRA DE NARANJA","descripcion"=>"Jugo de naranja","precio"=>"35","rubro_id"=>'6'],
            ["nombre"=>"1/2 JARRA DE NARANJA","descripcion"=>"Jugo de naranja","precio"=>"25","rubro_id"=>'6'],
            ["nombre"=>"JARRA DE LIMA","descripcion"=>"Jugo de lima","precio"=>"0","rubro_id"=>'6'],
            ["nombre"=>"1/2 JARRA DE LIMA","descripcion"=>"Jugo de lima","precio"=>"0","rubro_id"=>'6'],
            ["nombre"=>"JARRA DE MANZANA","descripcion"=>"Jugo de manzana","precio"=>"35","rubro_id"=>'6'],
            ["nombre"=>"1/2 JARRA DE MANZANA","descripcion"=>"Jugo de manzana","precio"=>"25","rubro_id"=>'6'],
            ["nombre"=>"JARRA DE TUMBO","descripcion"=>"Jugo de tumbo","precio"=>"0","rubro_id"=>'6'],
            ["nombre"=>"1/2 JARRA DE TUMBO","descripcion"=>"Jugo de tumbo","precio"=>"0","rubro_id"=>'6'],
            ["nombre"=>"JARRA DE MARACUYA","descripcion"=>"Jugo de maracuya","precio"=>"0","rubro_id"=>'6'],
            ["nombre"=>"1/2 JARRA DE MARACUYA","descripcion"=>"Jugo de maracuya","precio"=>"0","rubro_id"=>'6'],
            ["nombre"=>"JARRA DE UVA","descripcion"=>"Jugo de uva","precio"=>"0","rubro_id"=>'6'],
            ["nombre"=>"1/2 JARRA DE UVA","descripcion"=>"Jugo de uva","precio"=>"0","rubro_id"=>'6'],

            ["nombre"=>"COCA COLA 500 ml","descripcion"=>"","precio"=>"0","rubro_id"=>'7'],
            ["nombre"=>"FANTA 500 ml","descripcion"=>"","precio"=>"0","rubro_id"=>'7'],

            ["nombre"=>"CONTINENTAL","descripcion"=>"Tostadas o media luna, mantequilla, queso, mermelada, te o cafe (puro o con leche)","precio"=>"30","rubro_id"=>'8'],
            ["nombre"=>"AMERICANO","descripcion"=>"Zumo de naranja, lima o pomelo o tocino con huevos al gusto, tostadas, pan, media luna, mantequilla, mermelada, te o cafe(puro o con leche), ensalada de frutas","precio"=>"42","rubro_id"=>'8'],
            ["nombre"=>"CRIOLLO","descripcion"=>"Lomito de res con chorrellana, huevo frito, pan y papas fritas, acompañados de jugo o cafe","precio"=>"39","rubro_id"=>'8'],

            ["nombre"=>"OMELETTE MIXTO","descripcion"=>"Con jamon y queso","precio"=>"25","rubro_id"=>'9'],
            ["nombre"=>"OMELETTE DE POLLO","descripcion"=>"pechuga de pollo y papas fritas","precio"=>"25","rubro_id"=>'9'],
            ["nombre"=>"OMELETTE DE VERDURAS","descripcion"=>"Variedad de verduras frescas, acompañado con papas fritas","precio"=>"25","rubro_id"=>'9'],

            ["nombre"=>"KALHUA ICE CREAM","descripcion"=>"Dos porciones de helado de moca, licor de kalhua, chocolate caliente, crema y nuez picada","precio"=>"30","rubro_id"=>'10'],
            ["nombre"=>"SUPER HELADO","descripcion"=>"Ensalada de fruta,tres porciones de helado al gusto,salsa de fresa, nueces, manzana, crema, galleta y cherry","precio"=>"35","rubro_id"=>'10'],
            ["nombre"=>"CARNAVALERO","descripcion"=>"Ensalada de frutas, gelatina picada, helado de coco, vainilla y frutilla, crema, salsa de fresa y confites de color","precio"=>"28","rubro_id"=>'10'],
            ["nombre"=>"CARNAVALERO JR","descripcion"=>"Ensalada de frutas, gelatina picada, helado de chocolote y frutilla, crema, salsa de fresa y confites de color en un vaso infantil","precio"=>"23","rubro_id"=>'10'],
            ["nombre"=>"SUPER OREO","descripcion"=>"Tres porciones de helado oreo, cafe frio, crema y galletas oreo","precio"=>"35","rubro_id"=>'10'],  
            ["nombre"=>"CARIBE","descripcion"=>"Piñas al jugo, tres porciones de helado, salsa de fresas, nueces, piñas, galletas y cherry","precio"=>"31","rubro_id"=>'10'],
            ["nombre"=>"REFRESQUIN","descripcion"=>"Batido de helado de canela con agua mineral y limon","precio"=>"0","rubro_id"=>'10'],
            ["nombre"=>"TORTA DE HELADO","descripcion"=>"Porcion de torta a gusto, dos porciones de helado, crema, cherry y durazno","precio"=>"32","rubro_id"=>'10'],
// CLASICO
            ["nombre"=>"MELVA","descripcion"=>"Papaya picada, gelatina, helado de chocolate, frutilla y vainilla, rodajas de duraznos, crema y cherry","precio"=>"28","rubro_id"=>'11'],
            ["nombre"=>"VIENESA","descripcion"=>"Cafe frio, helado de vainilla, crema, galleta y cherry","precio"=>"28","rubro_id"=>'11'],
            ["nombre"=>"SUNDAE","descripcion"=>"Durazno Picado, helado de vainilla, baño de chocolate caliente, crema y cherry ","precio"=>"28","rubro_id"=>'11'],
            ["nombre"=>"BANANA SPLIT","descripcion"=>"Banana, helado de chocolate, frutilla y vainilla, crema y baño de cholotate, nueces picadas, cherry, piña y uva","precio"=>"28","rubro_id"=>'11'],
            ["nombre"=>"ICE CREAM SODA","descripcion"=>"Helado de vainilla, salsa de fresas y sprite","precio"=>"28","rubro_id"=>'11'],
            ["nombre"=>"MILK SHAKE","descripcion"=>"Tres porciones de helado al gusto batido con leche y crema","precio"=>"28","rubro_id"=>'11'],
            ["nombre"=>"ESCOLAR","descripcion"=>"Helado de frutilla y vainilla, crema, baño de chocolate, cherry y galleta","precio"=>"25","rubro_id"=>'11'],
            ["nombre"=>"SURTIDO","descripcion"=>"Tres porciones de helado, crema y cherry","precio"=>"25","rubro_id"=>'11'],
//CHOCOMANIA
            ["nombre"=>"CHOCOLATE HELADO","descripcion"=>"Chocolate frio, helado de chocolate, baño de chocolate caliente y crema","precio"=>"28","rubro_id"=>'12'],
            ["nombre"=>"CHOCOLATE FLOSH","descripcion"=>"Helado de chocolate con creama baño de chocolate caliente y cherry","precio"=>"28","rubro_id"=>'12'],
//ICE BRINDIS
            ["nombre"=>"SUPER WISKY","descripcion"=>"Batido de helado de chirimoya con wisky, crema, chocolate rallado, cherry, uva y piña","precio"=>"35","rubro_id"=>'13'],
            ["nombre"=>"BOMBON IRLANDES","descripcion"=>"Batido helado dulce de leche y chocolate con ron, crema, chocolate reallado, cherry, uva y piña","precio"=>"35","rubro_id"=>'13'],
            ["nombre"=>"UNIVERSITARIO","descripcion"=>"Helado de tumbo batido con singani brandy, limon, creama, piña y cherry","precio"=>"33","rubro_id"=>'13'],
            ["nombre"=>"JAMAICA","descripcion"=>"Batido de helado de limon con licor de menta, crema, coco rallado, cherry, uva y piña","precio"=>"33","rubro_id"=>'13'],
            ["nombre"=>"RUSA","descripcion"=>"Cerezas maceradas al vodka, helado de frutilla, salsa de fresas, crema y cherry","precio"=>"35","rubro_id"=>'13'],

            ["nombre"=>"FRUTILLA","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"VAINILLA","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"DULCE DE LECHE","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"OSO CREMOSO","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"CHICLE","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"SNICKER","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"MANDARINA","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"MOCA","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"CANELA","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"PISTACHO","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"CHOCOLATE","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"CHIRIMOYA","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"GRANIZADO","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"LIMON","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"PAI DE LIMON","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"KIWI","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"MORA","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"PASAS AL RON","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"COCO","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"MANJAR CON NUEZ","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"CAPUCHINO","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"MARACUYA","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"OREJON","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"TUMBO","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"DURAZNO","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"NUEZ","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],
            ["nombre"=>"CHOOCOLATE BLANCO","descripcion"=>"","precio"=>"0","rubro_id"=>'14'],

            ["nombre"=>"SUPER HAMBURGUESA","descripcion"=>"Hamburguesa doble con queso, huevo, hot dog, jamon y tocino acompañado de papas fritas y buffet de ensaladas + jugo o soda","precio"=>"44","rubro_id"=>'15','tipo'=>'COMBO'],
            ["nombre"=>"COMBO ESCOLAR","descripcion"=>"1 presa de pollo acompañado de papas fritas, platanos fritos y buffet de ensaladas + jugo o soda","precio"=>"26","rubro_id"=>'15','tipo'=>'COMBO'],
            ["nombre"=>"COMBO DUO","descripcion"=>"2 presas de pollo acompañado de papas fritas, platanos fritos y buffet de ensaladas + jugo o soda ","precio"=>"34","rubro_id"=>'15','tipo'=>'COMBO'],
            ["nombre"=>"COMBO TRIO","descripcion"=>"3 presas de pollo acompañado de papas fritas, platanos fritos y buffet de ensaladas + jugo o soda","precio"=>"42","rubro_id"=>'15','tipo'=>'COMBO'],
            ["nombre"=>"SUPER COMBO","descripcion"=>"5 presas de pollo acompañado de papas fritas, platanos fritos y buffet de ensaladas + jugo o soda","precio"=>"56","rubro_id"=>'15','tipo'=>'COMBO'],
            ["nombre"=>"SALCHIPAPAS","descripcion"=>"Salchicha vienesa acompañado de papas fritas, platanos fritos y buffet de ensaladas","precio"=>"22","rubro_id"=>'15'],
            ["nombre"=>"ALBONDIPAPAS DE POLLO O CARNE","descripcion"=>"Pequeñas albondigas acompañado de papas fritas, platanos fritos y buffet de ensaladas","precio"=>"32","rubro_id"=>'15'],
            ["nombre"=>"PIPOCAS DE POLLO","descripcion"=>"Trocitos de pechuga de pollo acompañado de papas fritas, platanos fritos y buffet de ensaladas","precio"=>"32","rubro_id"=>'15'],

            ["nombre"=>"PIZZA 4 QUESOS JUMBO","descripcion"=>"Masa delgada, salsa de tomate, queso roquefort, queso parmesano, queso mozzarella, queso chaqueño","precio"=>"","rubro_id"=>'16'],
            ["nombre"=>"PIZZA 4 QUESOS FAMILIAR","descripcion"=>"Masa delgada, salsa de tomate, queso roquefort, queso parmesano, queso mozzarella, queso chaqueño","precio"=>"","rubro_id"=>'16'],
            ["nombre"=>"PIZZA 4 QUESOS MEDIANA","descripcion"=>"Masa delgada, salsa de tomate, queso roquefort, queso parmesano, queso mozzarella, queso chaqueño","precio"=>"","rubro_id"=>'16'],
            ["nombre"=>"PIZZA CARNICERA JUMBO","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella (Parmesano / oregano) trozos de jamon, carne de res, chorizo italiano y tocino","precio"=>"90","rubro_id"=>'16'],
            ["nombre"=>"PIZZA CARNICERA FAMILIAR","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella (Parmesano / oregano) trozos de jamon, carne de res, chorizo italiano y tocino","precio"=>"70","rubro_id"=>'16'],
            ["nombre"=>"PIZZA CARNICERA MEDIANA","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella (Parmesano / oregano) trozos de jamon, carne de res, chorizo italiano y tocino","precio"=>"45","rubro_id"=>'16'],
            ["nombre"=>"PIZZA PEPERONI JUMBO","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella (Parmesano / oregano) y peperoni","precio"=>"90","rubro_id"=>'16'],
            ["nombre"=>"PIZZA PEPERONI FAMILIAR","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella (Parmesano / oregano) y peperoni","precio"=>"70","rubro_id"=>'16'],
            ["nombre"=>"PIZZA PEPERONI MEDIANA","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella (Parmesano / oregano) y peperoni","precio"=>"45","rubro_id"=>'16'],
            ["nombre"=>"PIZZA JAMON CON QUESO JUMBO","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella (Parmesano / oregano) y jamon","precio"=>"90","rubro_id"=>'16'],
            ["nombre"=>"PIZZA JAMON CON QUESO FAMILIAR","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella (Parmesano / oregano) y jamon","precio"=>"70","rubro_id"=>'16'],
            ["nombre"=>"PIZZA JAMON CON QUESO MEDIANA","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella (Parmesano / oregano) y jamon","precio"=>"45","rubro_id"=>'16'],
            ["nombre"=>"PIZZA SUPREMA JUMBO","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella, mix tomate - cebolla blanca, pimenton rojo verde, mix champiñones, chorizo italiano, peperoni","precio"=>"90","rubro_id"=>'16'],
            ["nombre"=>"PIZZA SUPREMA FAMILIAR","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella, mix tomate - cebolla blanca, pimenton rojo verde, mix champiñones, chorizo italiano, peperoni","precio"=>"70","rubro_id"=>'16'],
            ["nombre"=>"PIZZA SUPREMA MEDIANA","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella, mix tomate - cebolla blanca, pimenton rojo verde, mix champiñones, chorizo italiano, peperoni","precio"=>"45","rubro_id"=>'16'],
            ["nombre"=>"PIZZA JAMON CON CHAMPIÑONES JUMBO","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella (Parmesano / oregano) jamon y champiñones","precio"=>"90","rubro_id"=>'16'],
            ["nombre"=>"PIZZA JAMON CON CHAMPIÑONES FAMILIAR","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella (Parmesano / oregano) jamon y champiñones","precio"=>"70","rubro_id"=>'16'],
            ["nombre"=>"PIZZA JAMON CON CHAMPIÑONES MEDIANA","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella (Parmesano / oregano) jamon y champiñones","precio"=>"45","rubro_id"=>'16'],
            ["nombre"=>"PIZZA VEGETARIANA JUMBO","descripcion"=>"Masa delgada, salsa de ricota, queso mozarrella (Parmesano / oregano) variedad de verduras","precio"=>"90","rubro_id"=>'16'],
            ["nombre"=>"PIZZA VEGETARIANA FAMILIAR","descripcion"=>"Masa delgada, salsa de ricota, queso mozarrella (Parmesano / oregano) variedad de verduras","precio"=>"70","rubro_id"=>'16'],
            ["nombre"=>"PIZZA VEGETARIANA MEDIANA","descripcion"=>"Masa delgada, salsa de ricota, queso mozarrella (Parmesano / oregano) variedad de verduras","precio"=>"45","rubro_id"=>'16'],
            ["nombre"=>"PIZZA HAWAINA JUMBO","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella (Parmesano / oregano) trozos de jamon, piña, duraznos y cherry","precio"=>"90","rubro_id"=>'16'],
            ["nombre"=>"PIZZA HAWAINA FAMILIAR","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella (Parmesano / oregano) trozos de jamon, piña, duraznos y cherry","precio"=>"70","rubro_id"=>'16'],
            ["nombre"=>"PIZZA HAWAINA MEDIANA","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella (Parmesano / oregano) trozos de jamon, piña, duraznos y cherry","precio"=>"45","rubro_id"=>'16'],
            ["nombre"=>"PIZZA CAPRICHOSA JUMBO","descripcion"=>"Masa delgada, salsa de tomate, jamon, queso mozzarella, champiñones, esparragos, aceitunas verdes, albahaca","precio"=>"90","rubro_id"=>'16'],
            ["nombre"=>"PIZZA CAPRICHOSA FAMILIAR","descripcion"=>"Masa delgada, salsa de tomate, jamon, queso mozzarella, champiñones, esparragos, aceitunas verdes, albahaca","precio"=>"70","rubro_id"=>'16'],
            ["nombre"=>"PIZZA CAPRICHOSA MEDIANA","descripcion"=>"Masa delgada, salsa de tomate, jamon, queso mozzarella, champiñones, esparragos, aceitunas verdes, albahaca","precio"=>"45","rubro_id"=>'16'],
            ["nombre"=>"PIZZA BBQ BURGER JUMBO","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella, hamburguesa, tocino, cebolla en aros, salsa BBQ","precio"=>"0","rubro_id"=>'16'],
            ["nombre"=>"PIZZA BBQ BURGER FAMILIAR","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella, hamburguesa, tocino, cebolla en aros, salsa BBQ","precio"=>"0","rubro_id"=>'16'],
            ["nombre"=>"PIZZA BBQ BURGER MEDIANA","descripcion"=>"Masa delgada, salsa de tomate, queso mozzarella, hamburguesa, tocino, cebolla en aros, salsa BBQ","precio"=>"0","rubro_id"=>'16'],
            ["nombre"=>"PIZZA PALMITO JUMBO","descripcion"=>"Salsa de tomate, queso mozzarella, jamon, rodajas de palmito, tomate natural, aceitunas negras, salsa golf","precio"=>"0","rubro_id"=>'16'],
            ["nombre"=>"PIZZA PALMITO FAMILIAR","descripcion"=>"Salsa de tomate, queso mozzarella, jamon, rodajas de palmito, tomate natural, aceitunas negras, salsa golf","precio"=>"0","rubro_id"=>'16'],
            ["nombre"=>"PIZZA PALMITO MEDIANA","descripcion"=>"Salsa de tomate, queso mozzarella, jamon, rodajas de palmito, tomate natural, aceitunas negras, salsa golf","precio"=>"0","rubro_id"=>'16'],

            ["nombre"=>"COMBO 1","descripcion"=>"1 Hamburguesa simple + Papas fritas + 1 jugo o gaseosa","precio"=>"0","rubro_id"=>'17'],
            ["nombre"=>"COMBO 2","descripcion"=>"1 Hamburguesa + Queso o Huevo o Hot Dog + Papas fritas + 1 jugo o gaseosa","precio"=>"0","rubro_id"=>'17'],
            ["nombre"=>"COMBO 3","descripcion"=>"1 Hamburguesa con Jamon o Tocino + Papas fritas + 1 jugo o gaseosa","precio"=>"0","rubro_id"=>'17'],
            ["nombre"=>"COMBO 4","descripcion"=>"1 Hamburguesa Doble + Papas fritas + 1 jugo o gaseosa","precio"=>"0","rubro_id"=>'17'],
            ["nombre"=>"COMBO 5","descripcion"=>"1 Hamburguesa Doble + Queso o Huevo o Hot Dog + Papas fritas + 1 jugo o gaseosa","precio"=>"0","rubro_id"=>'17'],
            ["nombre"=>"COMBO 6","descripcion"=>"1 Hamburguesa Doble con jamon o Tocino + Papas fritas + 1 jugo o gaseosa","precio"=>"0","rubro_id"=>'17'],
            ["nombre"=>"SUPER COMBO","descripcion"=>"1 Hamburguesa Doble con Queso, Huevo, Hot Dog, Jamon y Tocino + Papas fritas + 1 jugo o gaseosa","precio"=>"0","rubro_id"=>'17'],
            
            ["nombre"=>"COMBO 1","descripcion"=>"Hamburguesa simple acompañado de Papas fritas y buffet de ensaladas + jugo o soda","precio"=>"23","rubro_id"=>'18',"tipo"=>"COMBO"],
            ["nombre"=>"COMBO 2","descripcion"=>"Hamburguesa con (queso, huevo o hot dog) acompañado de Papas fritas y buffet de ensaladas + jugo o soda","precio"=>"25","rubro_id"=>'18',"tipo"=>"COMBO"],
            ["nombre"=>"COMBO 3","descripcion"=>"Hamburguesa con jamon o tocino acompañado de Papas fritas y buffet de ensaladas + jugo o soda","precio"=>"28","rubro_id"=>'18',"tipo"=>"COMBO"],
            ["nombre"=>"COMBO 4","descripcion"=>"Hamburguesa doble acompañado de Papas fritas y buffet de ensaladas + jugo o soda","precio"=>"32","rubro_id"=>'18',"tipo"=>"COMBO"],
            ["nombre"=>"COMBO 5","descripcion"=>"Hamburguesa doble (queso, huevo o hot dog) acompañado de Papas fritas y buffet de ensaladas + jugo o soda","precio"=>"34","rubro_id"=>'18',"tipo"=>"COMBO"],
            ["nombre"=>"COMBO 6","descripcion"=>"Hamburguesa doble (Jamon o tocino) acompañado de Papas fritas y buffet de ensaladas + jugo o soda","precio"=>"36","rubro_id"=>'18',"tipo"=>"COMBO"],

            ["nombre"=>"SUPER PIQUE","descripcion"=>"Lomo y chorizo cortado en trozos, huevo duro, queso, papa frita, tomate, lechuga y cebolla","precio"=>"85","rubro_id"=>'19'],
            ["nombre"=>"SUPER MEDIO PIQUE","descripcion"=>"Lomo y chorizo cortado en trozos, huevo duro, queso, papa frita, tomate, lechuga y cebolla","precio"=>"70","rubro_id"=>'19'],
            ["nombre"=>"FILET MIGÑON","descripcion"=>"Lomito a la plancha con tocino cubierto con salsa de champiñones, arroz chaufa y papa frita","precio"=>"70","rubro_id"=>'19'],
            ["nombre"=>"MILANEZA DE POLLO","descripcion"=>"Milaneza con ensalada, arroz y papa frita","precio"=>"55","rubro_id"=>'19'],
            ["nombre"=>"MILANEZA NAPOLITANA","descripcion"=>"Milaneza con jamon y queso acompañado de aceitunas verdes, legumbres y papa frita","precio"=>"60","rubro_id"=>'19'],
            ["nombre"=>"SILPANCHO","descripcion"=>"Filete de lomito apanado papas fritas en rodajas, huevo frito, arroz y exquisita ensalada","precio"=>"60","rubro_id"=>'19'],
            ["nombre"=>"SUPER BROCHETA MIXTA","descripcion"=>"Carne de res y pollo con pimenton, cebolla en trozos acompañado de arroz y papa frita","precio"=>"60","rubro_id"=>'19'],
            ["nombre"=>"LAZAÑA","descripcion"=>"Exquisita pasta al estilo Italiano","precio"=>"0","rubro_id"=>'19'],
            ["nombre"=>"ALITAS PICANTES","descripcion"=>"Servidas con salsa picante, papas fritas y aros de cebolla","precio"=>"30","rubro_id"=>'19'],
            
            ["nombre"=>"CESAR","descripcion"=>"Deliciosa lechuga, anchoas, queso, crutones y aderezo","precio"=>"0","rubro_id"=>'20'],
            ["nombre"=>"JARDINERA DE POLLO","descripcion"=>"Variedad de legumbres con trocitos de pollo","precio"=>"35","rubro_id"=>'20'],
            ["nombre"=>"CHEFF","descripcion"=>"Variedad de legumbres, huevo, queso, jamones y salsa deliciosa","precio"=>"0","rubro_id"=>'20'],
            ["nombre"=>"JARDINERA","descripcion"=>"Variedad de legumbres frescas de la temporada y jamon","precio"=>"30","rubro_id"=>'20'],
            ["nombre"=>"JARDINERA CON ATUN","descripcion"=>"Variedad de legumbres frescas de la temporada y atun","precio"=>"35","rubro_id"=>'20'],

            ["nombre"=>"SANDWICH DE POLLO","descripcion"=>"Filete de pollo con lechuga, tomate, pepinillos al vinagre y papa frita","precio"=>"30","rubro_id"=>'21'],
            ["nombre"=>"SANDWICH MIXTO","descripcion"=>"Jamon y queso con lechuga, tomate pepinillo y papa frita","precio"=>"26","rubro_id"=>'21'],
            ["nombre"=>"SANDWICH DE LOMITO","descripcion"=>"Jugoso filete de res con lechuga, cebolla, tomate en pan baguette acompañado de papa frita","precio"=>"30","rubro_id"=>'21'],
            ["nombre"=>"SANDWICH DE LOMITO CON HUEVO","descripcion"=>"Jugoso filete de res con huevo, lechuga, cebolla, tomate en pan baguette acompañado de papa frita","precio"=>"34","rubro_id"=>'21'],
            ["nombre"=>"SANDWICH DE PHILADELFIA","descripcion"=>"Jugoso filete de res en tiritas con queso, tocino, champiñon, cebolla en pan baguette acompañado de papa frita","precio"=>"35","rubro_id"=>'21'],
            ["nombre"=>"SANDWICH DE PAVITA","descripcion"=>"Pechuga de pollo desmenuzada con mayoneza, pepinillo, lechuga, tomate, cebolla acompañado de papa frita","precio"=>"0","rubro_id"=>'21'],
            ["nombre"=>"SANDWICH DE CLUB","descripcion"=>"Pechuga de pollo con jamon, queso, huevo, tocino, lechuga, tomate, cebolla y pepinillo acompañado de papa frita","precio"=>"35","rubro_id"=>'21'],
            ["nombre"=>"SANDWICH DE HUEVO","descripcion"=>"Dos huevos fritos, lechuga, cebolla, tomate y pepinillo acompañado de papa frita","precio"=>"17","rubro_id"=>'21'],

            ["nombre"=>"ALFAFOR CON MANJAR","descripcion"=>"","precio"=>"7","rubro_id"=>'22'],
            ["nombre"=>"ALFAFOR CON CREMA","descripcion"=>"","precio"=>"7","rubro_id"=>'22'],
            ["nombre"=>"BROWNIE","descripcion"=>"","precio"=>"7","rubro_id"=>'22'],
            ["nombre"=>"NAPOLEON ","descripcion"=>"","precio"=>"7","rubro_id"=>'22'],
            ["nombre"=>"CANELON ","descripcion"=>"","precio"=>"7","rubro_id"=>'22'],
            ["nombre"=>"DONUTS ","descripcion"=>"","precio"=>"7","rubro_id"=>'22'],
            ["nombre"=>"ECLER ","descripcion"=>"","precio"=>"7","rubro_id"=>'22'],
            ["nombre"=>"BOMBITA ","descripcion"=>"","precio"=>"7","rubro_id"=>'22'],
            ["nombre"=>"LENGUA DE SUEGRA ","descripcion"=>"","precio"=>"6","rubro_id"=>'22'],
            ["nombre"=>"GOLOSO ","descripcion"=>"","precio"=>"7","rubro_id"=>'22'],
            ["nombre"=>"TARTALETA DE FRUTAS ","descripcion"=>"","precio"=>"7","rubro_id"=>'22'],
            ["nombre"=>"TARTALETA DE LIMON ","descripcion"=>"","precio"=>"7","rubro_id"=>'22'],
            ["nombre"=>"TARTALETA DE MANZANA ","descripcion"=>"","precio"=>"7","rubro_id"=>'22'],
            ["nombre"=>"NIDITO ","descripcion"=>"","precio"=>"7","rubro_id"=>'22'],
            ["nombre"=>"MEDIA LUNA ","descripcion"=>"","precio"=>"0","rubro_id"=>'22'],
            ["nombre"=>"TRUFA DE CHOCOLATE ","descripcion"=>"","precio"=>"7","rubro_id"=>'22'],
            ["nombre"=>"BERLINES","descripcion"=>"","precio"=>"7","rubro_id"=>'22'],
            ["nombre"=>"STRUDELL DE MANZANA","descripcion"=>"","precio"=>"0","rubro_id"=>'22'],
            ["nombre"=>"PALITOS DE ALMENDRA ","descripcion"=>"","precio"=>"5","rubro_id"=>'22'],
            ["nombre"=>"BRAZO GITANO ","descripcion"=>"","precio"=>"0","rubro_id"=>'22'],

            ["nombre"=>"EMPANADA DE QUESO ","descripcion"=>"","precio"=>"7","rubro_id"=>'23'],
            ["nombre"=>"EMPANADA DE HOJA ","descripcion"=>"","precio"=>"7","rubro_id"=>'23'],
            ["nombre"=>"ROLLITO DE QUESO ","descripcion"=>"","precio"=>"7","rubro_id"=>'23'],
            ["nombre"=>"CROSSANT DE QUESO","descripcion"=>"","precio"=>"7","rubro_id"=>'23'],
            ["nombre"=>"CROSSANT C/ JAMON Y QUESO","descripcion"=>"","precio"=>"7","rubro_id"=>'23'],
            ["nombre"=>"PALITOS DE QUESO","descripcion"=>"","precio"=>"5","rubro_id"=>'23'],
            ["nombre"=>"CUÑAPE","descripcion"=>"","precio"=>"7","rubro_id"=>'23'],
            ["nombre"=>"PAN PIZZA ","descripcion"=>"","precio"=>"7","rubro_id"=>'23'],
            ["nombre"=>"ENRROLLADO DE JAMON Y QUESO","descripcion"=>"","precio"=>"7","rubro_id"=>'23'],

            ["nombre"=>"FRUTILLA ","descripcion"=>"","precio"=>"20","rubro_id"=>'24'],
            ["nombre"=>"SELVA NEGRA ","descripcion"=>"","precio"=>"20","rubro_id"=>'24'],
            ["nombre"=>"DURAZNO","descripcion"=>"","precio"=>"20","rubro_id"=>'24'],
            ["nombre"=>"MOCA","descripcion"=>"","precio"=>"20","rubro_id"=>'24'],
            ["nombre"=>"NUEZ","descripcion"=>"","precio"=>"0","rubro_id"=>'24'],
            ["nombre"=>"CHOCOLATE ","descripcion"=>"","precio"=>"0","rubro_id"=>'24'],
            ["nombre"=>"ROSA NEGRA","descripcion"=>"","precio"=>"0","rubro_id"=>'24'],
            ["nombre"=>"CHOCOLATE ALEMAN","descripcion"=>"","precio"=>"0","rubro_id"=>'24'],
            ["nombre"=>"CANASTA","descripcion"=>"","precio"=>"0","rubro_id"=>'24'],
            ["nombre"=>"TIRAMISU","descripcion"=>"","precio"=>"0","rubro_id"=>'24'],
            ["nombre"=>"TROPICAL","descripcion"=>"","precio"=>"0","rubro_id"=>'24'],
            ["nombre"=>"UVA ","descripcion"=>"","precio"=>"0","rubro_id"=>'24'],
            ["nombre"=>"CHOCO VAINILLA ","descripcion"=>"","precio"=>"0","rubro_id"=>'24'],
            ["nombre"=>"OREO ","descripcion"=>"","precio"=>"0","rubro_id"=>'24'],
            ["nombre"=>"PIÑA ","descripcion"=>"","precio"=>"0","rubro_id"=>'24'],
            ["nombre"=>"CHOCO MERENGUE ","descripcion"=>"","precio"=>"0","rubro_id"=>'24'],
            ["nombre"=>"FRUTILLA ","descripcion"=>"","precio"=>"0","rubro_id"=>'24'],

            ["nombre"=>"ENSALADA DE FRFUTAS ","descripcion"=>"","precio"=>"30","rubro_id"=>'25'],
            ["nombre"=>"MUSH DE FRUTILLAS ","descripcion"=>"","precio"=>"0","rubro_id"=>'25'],
            ["nombre"=>"FLAN CASERO","descripcion"=>"","precio"=>"0","rubro_id"=>'25'],
            ["nombre"=>"ARLEQUIN","descripcion"=>"","precio"=>"0","rubro_id"=>'25'],
            ["nombre"=>"ASPIK DE FRUTAS","descripcion"=>"","precio"=>"0","rubro_id"=>'25'],
            ["nombre"=>"GELATINA CON CREMA","descripcion"=>"","precio"=>"0","rubro_id"=>'25'],
            ["nombre"=>"BUDIN","descripcion"=>"","precio"=>"0","rubro_id"=>'25'],
            ["nombre"=>"FLAN CASERO CN CREMA","descripcion"=>"","precio"=>"0","rubro_id"=>'25'],
            ["nombre"=>"PORCION DE CREMA","descripcion"=>"","precio"=>"8","rubro_id"=>'25'],

            ["nombre"=>"MOCHILA","rubro_id"=>'27'],          
            ["nombre"=>"MOANA","rubro_id"=>'27'],
            ["nombre"=>"INTENSAMENTE","rubro_id"=>'27'],
            ["nombre"=>"ZOMBIE","rubro_id"=>'27'],
            ["nombre"=>"LEGO PEQUEÑO","rubro_id"=>'27'],
            ["nombre"=>"LEGO GRANDE","rubro_id"=>'27'],
            ["nombre"=>"DINOSAURIO","rubro_id"=>'27'],
            ["nombre"=>"DRAGON BOLL","rubro_id"=>'27'],
            ["nombre"=>"FROZZEN","rubro_id"=>'27'],
            ["nombre"=>"SOFIA","rubro_id"=>'27'],
            ["nombre"=>"MINION","rubro_id"=>'27'],
            ["nombre"=>"PELOTA","rubro_id"=>'27'],
            ["nombre"=>"CAR","rubro_id"=>'27'],
            ["nombre"=>"TOY HISTORY","rubro_id"=>'27'], 
            ["nombre"=>"WAR CRAF","rubro_id"=>'27'],
            ["nombre"=>"OLAF","rubro_id"=>'27'],
            ["nombre"=>"PRINCESAS","rubro_id"=>'27'],
            ["nombre"=>"STAR WARS","rubro_id"=>'27'],
            ["nombre"=>"JUGUETE COCO","rubro_id"=>'27'],
            ["nombre"=>"STAR WARS JUGUETE","rubro_id"=>'27'],
            ["nombre"=>"AVENGERS 2","rubro_id"=>'27'],
            ["nombre"=>"MOANA","rubro_id"=>'27'],
            ["nombre"=>"MASHA","rubro_id"=>'27'],
            ["nombre"=>"LADY BOO GOMITA","rubro_id"=>'27'],
            ["nombre"=>"SOY LUNA","rubro_id"=>'27'],
            ["nombre"=>"LEGO SUPER HEROES","rubro_id"=>'27'],
            ["nombre"=>"LEGO CARS","rubro_id"=>'27'],
            ["nombre"=>"HEROES EN PIYAMAS","rubro_id"=>'27'],
            ["nombre"=>"MUÑECO GRINCH","rubro_id"=>'27'],
            ["nombre"=>"POP","rubro_id"=>'27'],
            ["nombre"=>"LOL","rubro_id"=>'27'],
            ["nombre"=>"VAMPIRINA","rubro_id"=>'27'],

            
        ]);
    }
}
